# -*- coding: utf-8 -*-
"""Beginner00.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e_7gNpBD1PmRM_QFcRG55hZSHEXAqSzf
"""

from google.colab import files
uploaded = files.upload()

# You need to import the pandas and seaborn library
import pandas as pd
import seaborn as sns

#You have to reproduce this graph

# Read the data from the CSV file with read from pandas
data = pd.read_csv("Salary_dataset.csv")


# Configure the style
sns.set_theme() #default

# Plot the data points with seaborn
sns.jointplot(data=data, x="YearsExperience", y="Salary", color="#9c90c1",)

# We're going to use this library and find out how it works on the Internet
from sklearn.linear_model import LinearRegression

# Separate the features (YearsExperience) from the target variable (Salary)
X = data[["YearsExperience"]].values # [[]] = 2 square brackets for dataframe, 1 for series
y = data["Salary"]


# Create a linear regression model
regression = LinearRegression().fit(X, y)

# Predict the Salary values based on YearsExperience
predictions = regression.predict(X)

#You have to reproduce this graph

# Create a linear regression plot using lmplot
graph = sns.lmplot(data=data, x="YearsExperience", y="Salary", aspect=1.5)

# Set labels and title
graph.set_axis_labels("Years of Experience", "Salary", fontsize=10)
graph.fig.suptitle("Linear Regression: Years of Experience vs Salary", y=1, fontsize=10)

# You should have these results with 10 years of expertise, so it's up to you to do your own tests

# Years of experience of the person you want to predict the salary for
years_experience = 10

# Predict the salary
#predicted_salary = regression.predict(pd.DataFrame({'YearsExperience': [years_experience]}))
predicted_salary = regression.predict([[years_experience]])

# Display the predicted salary
print(f"Predicted salary for {years_experience} years of experience : {predicted_salary[0]}")

# Display salary in Brazilian Reais
formatted = f"R$ {predicted_salary[0]:,.2f}".replace(',', 'X').replace('.', ',').replace('X', '.')
print(f"Predicted monthly salary in Brazilian Reais for {years_experience} years of experience : {formatted}")

